version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "412:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;User=admin;Password=Milton1103.;Database=Registration;Trusted_Connection=True;MultipleActiveResultSets=True;TrustServerCertificate=True;

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "413:80"
    depends_on:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Milton1103."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
